FROM centos:7

MAINTAINER Dmitriy Andrushko version:0.1

RUN yum -y install epel-release
RUN yum -y install git
RUN (curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" && python get-pip.py)
RUN yum -y install gcc gcc-с++ python-devel sudo deltarpm
RUN yum install -y initscripts openssh-server systemd-sysv openssl-1.0.2k \
    libselinux-utils logrotate python-setuptools \
    python-backports python-backports-ssl_match_hostname which
RUN ssh-keygen -A

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

EXPOSE 22 80 443 5671 5672 53333

# Should help to stop the container gracfully
STOPSIGNAL SIGRTMIN+3

RUN systemctl set-default multi-user.target
VOLUME [ "/sys/fs/cgroup" ]
CMD ["/bin/bash", "-c", "exec /sbin/init --log-target=journal 3>&1"]
